# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tab_widget.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(913, 652)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 871, 581))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(260, 40, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(120, 150, 281, 221))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_25)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_26)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_18.setObjectName("label_18")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_27)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_28)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_29)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_30)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_31)
        self.label_20 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_20.setObjectName("label_20")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.label_29 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_29.setObjectName("label_29")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.label_30 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_30.setObjectName("label_30")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.label_31 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_31.setObjectName("label_31")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.label_32 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_32.setObjectName("label_32")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.label_33 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_33.setObjectName("label_33")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_32)
        self.label_34 = QtWidgets.QLabel(self.tab)
        self.label_34.setGeometry(QtCore.QRect(120, 120, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.tab)
        self.label_35.setGeometry(QtCore.QRect(440, 120, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.listView = QtWidgets.QListView(self.tab)
        self.listView.setGeometry(QtCore.QRect(430, 150, 391, 221))
        self.listView.setObjectName("listView")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(120, 410, 701, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_22 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_4.addWidget(self.pushButton_22)
        self.pushButton_23 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_23.setObjectName("pushButton_23")
        self.horizontalLayout_4.addWidget(self.pushButton_23)
        self.pushButton_24 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_24.setObjectName("pushButton_24")
        self.horizontalLayout_4.addWidget(self.pushButton_24)
        self.pushButton_25 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_25.setObjectName("pushButton_25")
        self.horizontalLayout_4.addWidget(self.pushButton_25)
        self.pushButton_26 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_26.setObjectName("pushButton_26")
        self.horizontalLayout_4.addWidget(self.pushButton_26)
        self.pushButton_27 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_27.setObjectName("pushButton_27")
        self.horizontalLayout_4.addWidget(self.pushButton_27)
        self.pushButton_28 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_28.setObjectName("pushButton_28")
        self.horizontalLayout_4.addWidget(self.pushButton_28)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(270, 80, 400, 5))
        self.line.setMinimumSize(QtCore.QSize(400, 5))
        self.line.setMaximumSize(QtCore.QSize(400, 5))
        self.line.setSizeIncrement(QtCore.QSize(0, 2))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_36 = QtWidgets.QLabel(self.tab_2)
        self.label_36.setGeometry(QtCore.QRect(260, 80, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(120, 190, 281, 221))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.lineEdit_41 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_41)
        self.lineEdit_42 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_42)
        self.label_45 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_45.setObjectName("label_45")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_45)
        self.label_46 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_46.setObjectName("label_46")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_46)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_43)
        self.lineEdit_44 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_44)
        self.lineEdit_45 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_45)
        self.lineEdit_46 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.formLayout_6.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_46)
        self.lineEdit_47 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.formLayout_6.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_47)
        self.label_47 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_47.setObjectName("label_47")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_47)
        self.label_48 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_48.setObjectName("label_48")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_48)
        self.label_49 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_49.setObjectName("label_49")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_49)
        self.label_50 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_50.setObjectName("label_50")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_50)
        self.label_51 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_51.setObjectName("label_51")
        self.formLayout_6.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_51)
        self.label_52 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_52.setObjectName("label_52")
        self.formLayout_6.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_52)
        self.lineEdit_48 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_48)
        self.label_53 = QtWidgets.QLabel(self.tab_2)
        self.label_53.setGeometry(QtCore.QRect(120, 160, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.tab_2)
        self.label_54.setGeometry(QtCore.QRect(440, 160, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.listView_2 = QtWidgets.QListView(self.tab_2)
        self.listView_2.setGeometry(QtCore.QRect(430, 190, 391, 221))
        self.listView_2.setObjectName("listView_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(120, 450, 701, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_36 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_36.setObjectName("pushButton_36")
        self.horizontalLayout_6.addWidget(self.pushButton_36)
        self.pushButton_37 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_37.setObjectName("pushButton_37")
        self.horizontalLayout_6.addWidget(self.pushButton_37)
        self.pushButton_38 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_38.setObjectName("pushButton_38")
        self.horizontalLayout_6.addWidget(self.pushButton_38)
        self.pushButton_39 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_39.setObjectName("pushButton_39")
        self.horizontalLayout_6.addWidget(self.pushButton_39)
        self.pushButton_40 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_40.setObjectName("pushButton_40")
        self.horizontalLayout_6.addWidget(self.pushButton_40)
        self.pushButton_41 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_41.setObjectName("pushButton_41")
        self.horizontalLayout_6.addWidget(self.pushButton_41)
        self.pushButton_42 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_42.setObjectName("pushButton_42")
        self.horizontalLayout_6.addWidget(self.pushButton_42)
        self.line_2 = QtWidgets.QFrame(self.tab_2)
        self.line_2.setGeometry(QtCore.QRect(270, 120, 400, 5))
        self.line_2.setMinimumSize(QtCore.QSize(400, 5))
        self.line_2.setMaximumSize(QtCore.QSize(400, 5))
        self.line_2.setSizeIncrement(QtCore.QSize(0, 2))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 913, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_11.setText(_translate("MainWindow", "Student Database Management Systems"))
        self.label_18.setText(_translate("MainWindow", "Student ID:"))
        self.label_19.setText(_translate("MainWindow", "Firsr name:"))
        self.label_20.setText(_translate("MainWindow", "Surname:"))
        self.label_29.setText(_translate("MainWindow", "Day of birth:"))
        self.label_30.setText(_translate("MainWindow", "Age:"))
        self.label_31.setText(_translate("MainWindow", "Gender:"))
        self.label_32.setText(_translate("MainWindow", "Address:"))
        self.label_33.setText(_translate("MainWindow", "Mobile:"))
        self.label_34.setText(_translate("MainWindow", "Student Membership info:"))
        self.label_35.setText(_translate("MainWindow", "Book detail:"))
        self.pushButton_22.setText(_translate("MainWindow", "Add new"))
        self.pushButton_23.setText(_translate("MainWindow", "Display"))
        self.pushButton_24.setText(_translate("MainWindow", "Clear"))
        self.pushButton_25.setText(_translate("MainWindow", "Delete"))
        self.pushButton_26.setText(_translate("MainWindow", "Search"))
        self.pushButton_27.setText(_translate("MainWindow", "Update"))
        self.pushButton_28.setText(_translate("MainWindow", "Exit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.label_36.setText(_translate("MainWindow", "Student Database Management Systems"))
        self.label_45.setText(_translate("MainWindow", "Student ID:"))
        self.label_46.setText(_translate("MainWindow", "Firsr name:"))
        self.label_47.setText(_translate("MainWindow", "Surname:"))
        self.label_48.setText(_translate("MainWindow", "Day of birth:"))
        self.label_49.setText(_translate("MainWindow", "Age:"))
        self.label_50.setText(_translate("MainWindow", "Gender:"))
        self.label_51.setText(_translate("MainWindow", "Address:"))
        self.label_52.setText(_translate("MainWindow", "Mobile:"))
        self.label_53.setText(_translate("MainWindow", "Student Membership info:"))
        self.label_54.setText(_translate("MainWindow", "Book detail:"))
        self.pushButton_36.setText(_translate("MainWindow", "Add new"))
        self.pushButton_37.setText(_translate("MainWindow", "Display"))
        self.pushButton_38.setText(_translate("MainWindow", "Clear"))
        self.pushButton_39.setText(_translate("MainWindow", "Delete"))
        self.pushButton_40.setText(_translate("MainWindow", "Search"))
        self.pushButton_41.setText(_translate("MainWindow", "Update"))
        self.pushButton_42.setText(_translate("MainWindow", "Exit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
